
title:               Plainionist
tagline:             'Plainionic Programmer'
description:         'Plainionic Programmer'
url:                 https://plainionist.github.io
baseurl:             ''
paginate:            15

author:
  name:              Plainionist
  url:               https://plainionist.github.io
  email:             

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: plainionist
  instagram:
  linkedin:
  pinterest:
  rss: rss # just type anything here for a working RSS icon
  twitter: Plainionist
  stackoverflow: users/9113457/plainionist # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: blog-jjyol5kzmx

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-112127128-1

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

permalink: /:title/